using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using KarpineRfid.App.Services;
using Microsoft.Maui;
using Microsoft.Maui.Storage;
using Microsoft.Maui.Controls;
using Microsoft.Maui.Controls;
using System;

namespace KarpineRfid.App.ViewModels
{
    public partial class SettingsViewModel : ObservableObject
    {
        private readonly ISessionStore _store;

        // Observable properties generated by CommunityToolkit
        [ObservableProperty]
        bool autoConnect;

        [ObservableProperty]
        bool beepEnabled;

        [ObservableProperty]
        string selectedTheme = "System"; // "System" | "Light" | "Dark"

        // Commands
        public IAsyncRelayCommand ClearDataCommand { get; }
        public IRelayCommand OpenAboutCommand { get; }

        public SettingsViewModel(ISessionStore store)
        {
            _store = store ?? throw new ArgumentNullException(nameof(store));

            // Load persisted preferences
            AutoConnect = Preferences.Get("AutoConnect", false);
            BeepEnabled = Preferences.Get("BeepEnabled", true);
            SelectedTheme = Preferences.Get("SelectedTheme", "System");

            ClearDataCommand = new AsyncRelayCommand(ExecuteClearDataAsync);
            OpenAboutCommand = new RelayCommand(ExecuteOpenAbout);

            // persist preferences when properties change
            PropertyChanged += SettingsViewModel_PropertyChanged;
        }

        private void SettingsViewModel_PropertyChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            if (e.PropertyName == nameof(AutoConnect))
                Preferences.Set("AutoConnect", AutoConnect);
            else if (e.PropertyName == nameof(BeepEnabled))
                Preferences.Set("BeepEnabled", BeepEnabled);
            else if (e.PropertyName == nameof(SelectedTheme))
            {
                Preferences.Set("SelectedTheme", SelectedTheme);
                ApplyTheme(SelectedTheme);
            }
        }

        public void SyncSelectedThemeWithApp()
        {
            var current = Application.Current?.UserAppTheme ?? AppTheme.Unspecified;
            SelectedTheme = current switch
            {
                AppTheme.Light => "Light",
                AppTheme.Dark => "Dark",
                _ => "System"
            };
        }

        private void ApplyTheme(string theme)
        {
            if (Application.Current == null) return;

            switch (theme)
            {
                case "Light":
                    Application.Current.UserAppTheme = AppTheme.Light;
                    break;
                case "Dark":
                    Application.Current.UserAppTheme = AppTheme.Dark;
                    break;
                default:
                    Application.Current.UserAppTheme = AppTheme.Unspecified;
                    break;
            }
        }

        private async Task ExecuteClearDataAsync()
        {
            var ok = await Application.Current.MainPage.DisplayAlert("Confirm", "Are you sure you want to delete all saved sessions? This cannot be undone.", "Delete", "Cancel");
            if (!ok) return;

            try
            {
                var list = await _store.GetAllSessionsAsync();
                foreach (var s in list)
                {
                    await _store.DeleteSessionAsync(s.SessionId);
                }

                await Application.Current.MainPage.DisplayAlert("Done", "All sessions cleared.", "OK");
            }
            catch (Exception ex)
            {
                await Application.Current.MainPage.DisplayAlert("Error", ex.Message, "OK");
            }
        }

        private void ExecuteOpenAbout()
        {
            _ = Shell.Current.GoToAsync("//about");
        }
    }
}

